# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bbabd0cdab8e755efaf5809afdd95c29ed022c2c093bd96fdf9ebfc0d5ad25cadb94e82b02e3ec9dfdf19d376471dede8b17d7b3d753f9719cb5eecbf7e4043

test:
  secret_key_base: 051c02f6091cf03d27c83b5635af04e77d15f378b8765fe110ccaeae10fd9404954640c7b162a47b7e321c21de5fc00efa1d2e16e029d8ea7cfcf97eedf54584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
